// Mapa explícito (em vez de `import * as Icons from 'lucide-react'`) para não
// puxar a biblioteca inteira de ícones pro bundle — só os que as categorias
// e contas realmente usam. Ao criar uma categoria/conta nova com ícone novo,
// adicione o nome aqui.
import {
  Wallet2,
  UtensilsCrossed,
  Car,
  Home,
  PartyPopper,
  HeartPulse,
  GraduationCap,
  Repeat,
  MoreHorizontal,
  Landmark,
  Briefcase,
  TrendingUp,
  PiggyBank,
  Plane,
  Sparkles,
  Gift,
  Smartphone,
  ShoppingBag,
  ShoppingCart,
  Shirt,
  Dumbbell,
  Dog,
  Baby,
  Coffee,
  Beer,
  Pizza,
  Bus,
  Fuel,
  Wrench,
  Scissors,
  Stethoscope,
  Pill,
  Book,
  Music,
  Film,
  Gamepad2,
  Palette,
  Camera,
  Plug,
  Wifi,
  Droplet,
  Flame,
  Receipt,
  CreditCard,
  Banknote,
  TrendingDown,
  Building2,
  Users,
  Heart,
  Church,
  Trees,
  Umbrella,
  Tag,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const MAPA: Record<string, LucideIcon> = {
  Wallet2,
  UtensilsCrossed,
  Car,
  Home,
  PartyPopper,
  HeartPulse,
  GraduationCap,
  Repeat,
  MoreHorizontal,
  Landmark,
  Briefcase,
  TrendingUp,
  PiggyBank,
  Plane,
  Sparkles,
  Gift,
  Smartphone,
  ShoppingBag,
  ShoppingCart,
  Shirt,
  Dumbbell,
  Dog,
  Baby,
  Coffee,
  Beer,
  Pizza,
  Bus,
  Fuel,
  Wrench,
  Scissors,
  Stethoscope,
  Pill,
  Book,
  Music,
  Film,
  Gamepad2,
  Palette,
  Camera,
  Plug,
  Wifi,
  Droplet,
  Flame,
  Receipt,
  CreditCard,
  Banknote,
  TrendingDown,
  Building2,
  Users,
  Heart,
  Church,
  Trees,
  Umbrella,
  Tag,
}

// Ícones oferecidos no seletor da tela de Categorias — subconjunto do MAPA
// acima, dividido por tipo pra facilitar achar algo relevante na hora de
// criar/editar. Mantém a mesma fonte de verdade (o MAPA) então qualquer
// ícone escolhido aqui sempre resolve certo em iconePorNome.
export const ICONES_DESPESA = [
  'UtensilsCrossed', 'ShoppingCart', 'ShoppingBag', 'Car', 'Bus', 'Fuel',
  'Home', 'Flame', 'Droplet', 'Wifi', 'Plug', 'Wrench',
  'HeartPulse', 'Stethoscope', 'Pill', 'Dumbbell',
  'GraduationCap', 'Book', 'Music', 'Film', 'Gamepad2', 'PartyPopper', 'Palette', 'Camera',
  'Repeat', 'Smartphone', 'Shirt', 'Scissors', 'Coffee', 'Beer', 'Pizza',
  'Dog', 'Baby', 'Users', 'Heart', 'Church', 'Gift', 'Plane', 'Trees', 'Umbrella',
  'Receipt', 'CreditCard', 'Tag', 'MoreHorizontal',
]

export const ICONES_RECEITA = [
  'Landmark', 'Briefcase', 'TrendingUp', 'Banknote', 'PiggyBank',
  'Building2', 'Gift', 'Repeat', 'Tag', 'MoreHorizontal',
]

export function iconePorNome(nome: string): LucideIcon {
  return MAPA[nome] ?? Wallet2
}
